/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSlugRouteImport } from './routes/sessions/$slug'
import { Route as GroupsSplatRouteImport } from './routes/groups/$'
import { Route as DevMarkdownRouteImport } from './routes/dev/markdown'
import { Route as DevDiffRouteImport } from './routes/dev/diff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSlugRoute = SessionsSlugRouteImport.update({
  id: '/sessions/$slug',
  path: '/sessions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSplatRoute = GroupsSplatRouteImport.update({
  id: '/groups/$',
  path: '/groups/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMarkdownRoute = DevMarkdownRouteImport.update({
  id: '/dev/markdown',
  path: '/dev/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiffRoute = DevDiffRouteImport.update({
  id: '/dev/diff',
  path: '/dev/diff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
  '/groups/$': typeof GroupsSplatRoute
  '/sessions/$slug': typeof SessionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
  '/groups/$': typeof GroupsSplatRoute
  '/sessions/$slug': typeof SessionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
  '/groups/$': typeof GroupsSplatRoute
  '/sessions/$slug': typeof SessionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/diff'
    | '/dev/markdown'
    | '/groups/$'
    | '/sessions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev/diff' | '/dev/markdown' | '/groups/$' | '/sessions/$slug'
  id:
    | '__root__'
    | '/'
    | '/dev/diff'
    | '/dev/markdown'
    | '/groups/$'
    | '/sessions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevDiffRoute: typeof DevDiffRoute
  DevMarkdownRoute: typeof DevMarkdownRoute
  GroupsSplatRoute: typeof GroupsSplatRoute
  SessionsSlugRoute: typeof SessionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$slug': {
      id: '/sessions/$slug'
      path: '/sessions/$slug'
      fullPath: '/sessions/$slug'
      preLoaderRoute: typeof SessionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$': {
      id: '/groups/$'
      path: '/groups/$'
      fullPath: '/groups/$'
      preLoaderRoute: typeof GroupsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/markdown': {
      id: '/dev/markdown'
      path: '/dev/markdown'
      fullPath: '/dev/markdown'
      preLoaderRoute: typeof DevMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diff': {
      id: '/dev/diff'
      path: '/dev/diff'
      fullPath: '/dev/diff'
      preLoaderRoute: typeof DevDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevDiffRoute: DevDiffRoute,
  DevMarkdownRoute: DevMarkdownRoute,
  GroupsSplatRoute: GroupsSplatRoute,
  SessionsSlugRoute: SessionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
