/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorktreesRouteImport } from './routes/worktrees'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevMarkdownRouteImport } from './routes/dev/markdown'
import { Route as DevDiffRouteImport } from './routes/dev/diff'

const WorktreesRoute = WorktreesRouteImport.update({
  id: '/worktrees',
  path: '/worktrees',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMarkdownRoute = DevMarkdownRouteImport.update({
  id: '/dev/markdown',
  path: '/dev/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiffRoute = DevDiffRouteImport.update({
  id: '/dev/diff',
  path: '/dev/diff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/worktrees': typeof WorktreesRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/worktrees': typeof WorktreesRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/worktrees': typeof WorktreesRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/worktrees' | '/dev/diff' | '/dev/markdown'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/worktrees' | '/dev/diff' | '/dev/markdown'
  id: '__root__' | '/' | '/$' | '/worktrees' | '/dev/diff' | '/dev/markdown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  WorktreesRoute: typeof WorktreesRoute
  DevDiffRoute: typeof DevDiffRoute
  DevMarkdownRoute: typeof DevMarkdownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worktrees': {
      id: '/worktrees'
      path: '/worktrees'
      fullPath: '/worktrees'
      preLoaderRoute: typeof WorktreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/markdown': {
      id: '/dev/markdown'
      path: '/dev/markdown'
      fullPath: '/dev/markdown'
      preLoaderRoute: typeof DevMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diff': {
      id: '/dev/diff'
      path: '/dev/diff'
      fullPath: '/dev/diff'
      preLoaderRoute: typeof DevDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  WorktreesRoute: WorktreesRoute,
  DevDiffRoute: DevDiffRoute,
  DevMarkdownRoute: DevMarkdownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
