/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevTerminalRouteImport } from './routes/dev/terminal'
import { Route as DevMarkdownRouteImport } from './routes/dev/markdown'
import { Route as DevDiffRouteImport } from './routes/dev/diff'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTerminalRoute = DevTerminalRouteImport.update({
  id: '/dev/terminal',
  path: '/dev/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMarkdownRoute = DevMarkdownRouteImport.update({
  id: '/dev/markdown',
  path: '/dev/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiffRoute = DevDiffRouteImport.update({
  id: '/dev/diff',
  path: '/dev/diff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sessions': typeof SessionsRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
  '/dev/terminal': typeof DevTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sessions': typeof SessionsRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
  '/dev/terminal': typeof DevTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sessions': typeof SessionsRoute
  '/dev/diff': typeof DevDiffRoute
  '/dev/markdown': typeof DevMarkdownRoute
  '/dev/terminal': typeof DevTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/sessions'
    | '/dev/diff'
    | '/dev/markdown'
    | '/dev/terminal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/sessions' | '/dev/diff' | '/dev/markdown' | '/dev/terminal'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/sessions'
    | '/dev/diff'
    | '/dev/markdown'
    | '/dev/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SessionsRoute: typeof SessionsRoute
  DevDiffRoute: typeof DevDiffRoute
  DevMarkdownRoute: typeof DevMarkdownRoute
  DevTerminalRoute: typeof DevTerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/terminal': {
      id: '/dev/terminal'
      path: '/dev/terminal'
      fullPath: '/dev/terminal'
      preLoaderRoute: typeof DevTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/markdown': {
      id: '/dev/markdown'
      path: '/dev/markdown'
      fullPath: '/dev/markdown'
      preLoaderRoute: typeof DevMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diff': {
      id: '/dev/diff'
      path: '/dev/diff'
      fullPath: '/dev/diff'
      preLoaderRoute: typeof DevDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SessionsRoute: SessionsRoute,
  DevDiffRoute: DevDiffRoute,
  DevMarkdownRoute: DevMarkdownRoute,
  DevTerminalRoute: DevTerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
