import { Fragment } from "react";
import { useQuery } from "@tanstack/react-query";

import { Badge, Group, Text } from "@uiid/design-system";

import { statsQuery } from "../../api/queries";
import type { SessionStatsRow } from "../../api/types";
import { formatTokens } from "../../lib/format";
import { standingFor, usagePeers } from "../../lib/usage-standing";
import { useAllStats } from "../../lib/use-sessions";
import { SidebarZone } from "../sidebar/subcomponents/sidebar-zone";

export type UsageZoneProps = {
  /** The session the sidebar belongs to — only its usage is shown. */
  sessionId: string;
  /** Live sessions poll as tokens accrue; paused ones fetch once. */
  isLive?: boolean;
};

/**
 * The four counters, deliberately never summed. Cache reads run ~100x the
 * volume of output but bill at a fraction of it, so a single "total tokens"
 * figure would be ~99% cache reads and say nothing about what the session
 * cost. Output leads because it is the one that tracks work produced.
 */
const ROWS = [
  { key: "outputTokens", label: "Output", hint: "Generated by Claude" },
  { key: "inputTokens", label: "Input", hint: "Fresh context sent" },
  { key: "cacheReadTokens", label: "Cache read", hint: "Context reused" },
  {
    key: "cacheCreationTokens",
    label: "Cache write",
    hint: "Context written to cache",
  },
] as const satisfies ReadonlyArray<{
  key: keyof SessionStatsRow;
  label: string;
  hint: string;
}>;

/**
 * Collapsible "Token usage" section for the secondary sidebar. Totals are
 * rolled up from the session's conversations, where transcript ingestion
 * accrues them.
 *
 * The zone always renders, including when nothing was captured — it's a fixed
 * landmark like its neighbours. "None captured" is its own answer, and it
 * covers both a session that spent nothing and one predating usage capture
 * that hasn't been backfilled; the two are indistinguishable from here, so
 * the copy claims neither.
 */
export const UsageZone = ({ sessionId, isLive }: UsageZoneProps) => {
  const { data: stats, isPending } = useQuery({
    ...statsQuery(sessionId, isLive),
    enabled: !!sessionId,
  });

  // Peers give the counters a scale to be read against. Deliberately the same
  // set the primary sidebar ranks against — every known session, not just this
  // session's repo: the two badges sit on screen together, so a session that
  // reads "heavy" in one must read heavy in the other. Shares the sidebar's
  // cache entry, so this is usually free.
  const allStats = useAllStats();

  const captured = stats
    ? stats.inputTokens +
      stats.outputTokens +
      stats.cacheCreationTokens +
      stats.cacheReadTokens
    : 0;

  // Standing only means something against real numbers; with nothing captured
  // there's no peer comparison to draw, so the badge falls back to "none".
  const standing =
    stats && captured > 0
      ? standingFor(stats.outputTokens, usagePeers(allStats))
      : null;

  return (
    <SidebarZone
      data-slot="usage-zone"
      title="Token usage"
      badge={
        isPending ? null : standing && stats ? (
          <Badge color={standing.color} title={standing.title}>
            <Text size={-1} weight="bold">
              {formatTokens(stats.outputTokens)}
            </Text>
          </Badge>
        ) : (
          <Badge color="neutral" size="small">
            none
          </Badge>
        )
      }
      PanelProps={{ style: { paddingBlock: 8 } }}
    >
      {stats && captured > 0 ? (
        /* One grid for the whole list so the counts line up tabularly. */
        <Group
          px={2}
          gap={1}
          fullwidth
          style={{
            display: "grid",
            gridTemplateColumns: "minmax(0, 1fr) auto",
            columnGap: 12,
          }}
        >
          {ROWS.map(({ key, label, hint }) => (
            <Fragment key={key}>
              <Text size={-1} shade="muted" title={hint}>
                {label}
              </Text>
              <Text
                size={-1}
                family="mono"
                title={`${(stats[key] as number).toLocaleString()} tokens — ${hint}`}
                style={{
                  textAlign: "right",
                  fontVariantNumeric: "tabular-nums",
                }}
              >
                {formatTokens(stats[key] as number)}
              </Text>
            </Fragment>
          ))}
        </Group>
      ) : (
        <Group px={2} fullwidth>
          {/* Zeroed counters would assert this session spent nothing, which
              isn't knowable here — a session predating usage capture reads
              the same until its transcripts are backfilled. */}
          <Text
            size={-1}
            shade="muted"
            title="Sessions predating usage capture stay empty until their transcripts are backfilled."
          >
            {isPending ? "Checking…" : "No token usage captured."}
          </Text>
        </Group>
      )}
    </SidebarZone>
  );
};
UsageZone.displayName = "UsageZone";
