import { Fragment } from "react";
import { useQuery } from "@tanstack/react-query";

import { Badge, Group, Text } from "@uiid/design-system";

import { allStatsQuery, statsQuery } from "../../api/queries";
import type { SessionStatsRow } from "../../api/types";
import { formatTokens } from "../../lib/format";
import { standingFor, usagePeers } from "../../lib/usage-standing";
import { useSelectedProjects } from "../sidebar/selected-projects";
import { SidebarZone } from "../sidebar/subcomponents/sidebar-zone";

export type UsageZoneProps = {
  /** The session the sidebar belongs to — only its usage is shown. */
  sessionId: string;
  /** Live sessions poll as tokens accrue; paused ones fetch once. */
  isLive?: boolean;
  /** Project the session belongs to, so stats resolve against the right DB. */
  projectSlug?: string;
};

/**
 * The four counters, deliberately never summed. Cache reads run ~100x the
 * volume of output but bill at a fraction of it, so a single "total tokens"
 * figure would be ~99% cache reads and say nothing about what the session
 * cost. Output leads because it is the one that tracks work produced.
 */
const ROWS = [
  { key: "outputTokens", label: "Output", hint: "Generated by Claude" },
  { key: "inputTokens", label: "Input", hint: "Fresh context sent" },
  { key: "cacheReadTokens", label: "Cache read", hint: "Context reused" },
  { key: "cacheCreationTokens", label: "Cache write", hint: "Context written to cache" },
] as const satisfies ReadonlyArray<{
  key: keyof SessionStatsRow;
  label: string;
  hint: string;
}>;

/**
 * Collapsible "Token usage" section for the secondary sidebar. Totals are
 * rolled up from the session's conversations, where transcript ingestion
 * accrues them. Renders nothing when nothing has been captured — an empty
 * zone is noise, not signal — which also keeps it hidden for sessions
 * predating usage capture until they are backfilled.
 */
export const UsageZone = ({
  sessionId,
  isLive,
  projectSlug,
}: UsageZoneProps) => {
  const { data: stats } = useQuery({
    ...statsQuery(sessionId, isLive, projectSlug),
    enabled: !!sessionId,
  });

  // Peers give the counters a scale to be read against. Deliberately the same
  // selection the primary sidebar ranks against, not this session's project:
  // the two badges sit on screen together, so a session that reads "heavy" in
  // one must read heavy in the other. Already cached by the sessions list, so
  // this is usually free.
  const { queryProjects } = useSelectedProjects();
  const { data: allStats } = useQuery(
    allStatsQuery({ hasLiveSession: isLive, projects: queryProjects }),
  );

  if (!stats) return null;

  const captured =
    stats.inputTokens +
    stats.outputTokens +
    stats.cacheCreationTokens +
    stats.cacheReadTokens;
  if (captured === 0) return null;

  const standing = standingFor(stats.outputTokens, usagePeers(allStats));

  return (
    <SidebarZone
      data-slot="usage-zone"
      title="Token usage"
      badge={
        <Badge color={standing.color} title={standing.title}>
          <Text size={-1} weight="bold">
            {formatTokens(stats.outputTokens)}
          </Text>
        </Badge>
      }
      PanelProps={{ style: { paddingBlock: 8 } }}
    >
      {/* One grid for the whole list so the counts line up tabularly. */}
      <Group
        px={2}
        gap={1}
        fullwidth
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0, 1fr) auto",
          columnGap: 12,
        }}
      >
        {ROWS.map(({ key, label, hint }) => (
          <Fragment key={key}>
            <Text size={-1} shade="muted" title={hint}>
              {label}
            </Text>
            <Text
              size={-1}
              family="mono"
              title={`${(stats[key] as number).toLocaleString()} tokens — ${hint}`}
              style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}
            >
              {formatTokens(stats[key] as number)}
            </Text>
          </Fragment>
        ))}
      </Group>
    </SidebarZone>
  );
};
UsageZone.displayName = "UsageZone";
