import { eq, and, desc } from "drizzle-orm";
import { getDb } from "../client.ts";
import { conversations } from "../schema.ts";

export function createConversation(opts: {
  id: string; // claude_id UUID — generated by bertrand, passed to claude via --session-id
  sessionId: string;
}) {
  return getDb()
    .insert(conversations)
    .values(opts)
    .returning()
    .get();
}

export function getConversation(id: string) {
  return getDb()
    .select()
    .from(conversations)
    .where(eq(conversations.id, id))
    .get();
}

export function getConversationsBySession(sessionId: string) {
  return getDb()
    .select()
    .from(conversations)
    .where(
      and(
        eq(conversations.sessionId, sessionId),
        eq(conversations.discarded, false)
      )
    )
    .orderBy(desc(conversations.startedAt))
    .all();
}

export function endConversation(id: string) {
  return getDb()
    .update(conversations)
    .set({ endedAt: new Date().toISOString() })
    .where(eq(conversations.id, id))
    .returning()
    .get();
}

export function discardConversation(id: string) {
  return getDb()
    .update(conversations)
    .set({ discarded: true })
    .where(eq(conversations.id, id))
    .returning()
    .get();
}

export function updateConversationEventCount(id: string, count: number) {
  return getDb()
    .update(conversations)
    .set({ eventCount: count })
    .where(eq(conversations.id, id))
    .returning()
    .get();
}

export function updateLastQuestion(id: string, question: string) {
  return getDb()
    .update(conversations)
    .set({ lastQuestion: question })
    .where(eq(conversations.id, id))
    .returning()
    .get();
}
